### ISSUE TITLE
Using `pnpm moonwall run zombie_tanssi_warp_sync` errors

### ISSUE THREAD

**Issue by Chralt98** [moondance-labs/tanssi#303]
The error message is the following:

```
node:fs:1452
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/user/development/tanssi/test/tmp/node_logs'
    at Object.readdirSync (node:fs:1452:3)
    at reportLogLocation (file:///Users/user/development/tanssi/node_modules/.pnpm/@moonwall+cli@4.1.6_@types+node@20.5.6_@vitest+ui@0.33.0_typescript@5.2.2/node_modules/@moonwall/cli/dist/chunk-LXB5S76P.js:18:21)
    at runNetworkCmd (file:///Users/user/development/tanssi/node_modules/.pnpm/@moonwall+cli@4.1.6_@types+node@20.5.6_@vitest+ui@0.33.0_typescript@5.2.2/node_modules/@moonwall/cli/dist/chunk-KOVVJTEW.js:127:3)
    at async Object.handler (file:///Users/user/development/tanssi/node_modules/.pnpm/@moonwall+cli@4.1.6_@types+node@20.5.6_@vitest+ui@0.33.0_typescript@5.2.2/node_modules/@moonwall/cli/dist/cmds/entrypoint.js:123:5) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/user/development/tanssi/test/tmp/node_logs'
}

Node.js v18.16.0
```

**Comment by Chralt98** [comment]
The fix is to execute `mkdir node_logs` inside the `test/tmp` folder. You could apply this to your scripts.

**Comment by tmpolaczyk** [comment]
Thanks, I reported your issue in the moonwall repo: https://github.com/Moonsong-Labs/moonwall/issues/295

And btw, you should be using node.js 20, I see in the error message that you are on 18 and that won't work.

Closing this, as the fix should be in moonwall.
